### ISSUE TITLE
XML compliance

### ISSUE THREAD

**Issue by sonnyp** [x-tag/x-tag#18]
Hi,

I think x-tag should be XML compliant whenever the document is a strict XML document. For exemple by using XML namespaces.
Would you merge a such patch?

**Comment by fwenzel** [comment]
What's the use case?

I'll leave the decision up to dbuc, but I don't think this would be a good chunk of code to maintain in this library. x-tag (the framework/shim as well as the individual components) is, at its core, an HTML5 project, built for HTML5 rendering engines. I would be highly reluctant to tie XML compliance into this and having to maintain this for all components to come.

**Comment by csuwildcat** [comment]
What would be the benefit of having an X-Tag output namespaced elements for XML? Also, I just removed the default namepace, so you can just add the namespaced string to the tag name you pass to xtag.register()

**Comment by sonnyp** [comment]
"What's the use case?"
XHTML5 or XUL or whatever XML based UI language.

"and having to maintain this for all components to come."
As far as I know there is no need to edit the components code.

"What would be the benefit of having an X-Tag output namespaced elements for XML?"
Avoid conflicts.

**Comment by sonnyp** [comment]
The removing of the default "x-" namespace should be enough for making XML compliance possible. I closed the bug.
