### ISSUE TITLE
Don't have two branches gh-pages and master

### ISSUE THREAD

**Issue by fwenzel** [x-tag/x-tag#2]
It seems silly that we have to maintain two branches (gh-pages and master). Will it suffice to just have gh-pages and just make that the main branch?

**Comment by fwenzel** [comment]
@pennyfx is the gh-pages branch still in use?

**Comment by pennyfx** [comment]
It's essentially a redirect for all the original links sent out to the blogosphere.

**Comment by fwenzel** [comment]
That's fixed then. I just didn't want to duplicate the library code on both sides.
