### ISSUE TITLE
Emit a custom event when xtag has processed the initial DOM tree

### ISSUE THREAD

**Issue by sonnyp** [x-tag/x-tag#23]
Here is a simple usecase:

``` html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>testcase</title>
    <meta charset="UTF-8"/>
    <script type="application/javascript" src="x-tag.js"></script>
    <script>
      xtag.register('foo', {
        methods: {
          foo: function() {
            alert('foo');
          }
        },
        getters: {
          bar: function(){
            alert('bar');
          },
        },
        setters: {
          bar: function(){
            alert('bar');
          },
        }
      });
      //doesn't works
      document.addEventListener('DOMContentLoaded', function() {
        var foo = document.querySelector('foo');
        foo.xtag.foo();
        foo.bar = 'foo';
      });
      //works
      document.addEventListener('DOMContentLoaded', function() {
        var foo = document.querySelector('foo');
        setTimeout(function() {
          foo.xtag.foo();
          foo.bar = 'foo';
        }, 1000);
      });
    </script>
  </head>
  <body>
    <foo/>
  </body>
</html>
```

**Comment by sonnyp** [comment]
By the way, why methods are held within a xtag object?

**Comment by csuwildcat** [comment]
Are you by chance running into an issue where getters and setters are not having effect? If so, that is actually (IMHO) a bad implementation point of native getters and setters, which X-Tag uses in all browsers. The native getter/setter methods blow away existing values when you attach them to a property. This can lead to what looks like silent failures of the getters and setters if you set or get values before attachment occurs. To combat this, I implemented a pseudo system (patterned after MooTools' event pseudos), and created a pseudo called :retain. if you use that in the key of your getters and setters, your existing values will be reset when the accessors are attached.

I can try and fire a DOMComponentsLoaded event, let me think about it a bit ;)

``` javascript
getters: {
    'bar:retain': function(){
        alert('bar');
    },
 },
setters: {
    'bar:retain': function(){
        alert('bar');
    },
}
```

**Comment by csuwildcat** [comment]
DOMComponentsLoaded event is now being emitted on the document, see this commit: https://github.com/mozilla/x-tag/pull/37

You can now do your getter/setter actions on elements within DOMContentLoaded event blocks to ensure the elements are ready. I removed the :retain pseudo as this is cleaner and affords the same capability.
