### ISSUE TITLE
Replace screenshots for slidebox and remove disclaimer

### ISSUE THREAD

**Issue by fwenzel** [x-tag/x-tag#3]
The disclaimer under the slidebox demo seems unnecessary overhead. Should we just use some Mozilla-themed photos and avoid the whole disclaimer thing?

**Comment by csuwildcat** [comment]
Feel free to remove it from any repo copy we make for Mozilla. I prefer to leave it in my personal branch as a f**\* you to the company (MetaLab) that used a proven lie to try and snag publicity on TechCrunch and personally character assassinate me. (not sure if you remember when all that happened)

Petty? Maybe. Deserving? Absolutely.

**Comment by csuwildcat** [comment]
Ugg, someone checked in a bug, give me a sec and I'll have it fixed :(

**Comment by csuwildcat** [comment]
Hmm, not seeing it broken on the live page... http://csuwldcat.github.com/x-tag/demo.html

**Comment by csuwildcat** [comment]
Should be fixed now.

**Comment by fwenzel** [comment]
Heh, all right.

**Comment by csuwildcat** [comment]
The last 4 comments are not for this ticket, Github posted those comments that were intended for the other bug to this one. The other issue is fixed, I'm leaving this one as is.

**Comment by csuwildcat** [comment]
I toned it down, just for you Fred, lol ;)

**Comment by fwenzel** [comment]
Yea that's what I figured.

**Comment by fwenzel** [comment]
Haha, ALL RIGHT ALL RIGHT :)
