### ISSUE TITLE
Tag registration requires x- prefix

### ISSUE THREAD

**Issue by matthewp** [x-tag/x-tag#31]
the onCreate event will not fire on page load if tags are registered without the x- prefix.  I'm not sure if that is intentional or not, but the informational page (http://mozilla.github.com/x-tag/) shows tags as being registered without the prefix.

**Comment by csuwildcat** [comment]
I had removed the requirement for prefixing of tags many days ago, where are you seeing this issue in the code?

**Comment by matthewp** [comment]
I didn't see it in the code, I saw it from testing.  I'll try to track down where the problem is.

**Comment by matthewp** [comment]
I now realize that this might be a misunderstanding.  I was putting the prefix in my html but not in the xtag.register call, expecting it to enforce the x- prefix in the html.  I now realize that it works if you remove the prefix from the html.

**Comment by csuwildcat** [comment]
Yeah, I remove that auto-prefixing mechanism, though I would still encourage you register your tags as "x-____" so as to avoid any future new HTML native tag compatibility issues.
