### ISSUE TITLE
methods vs. getters

### ISSUE THREAD

**Issue by matthewp** [x-tag/x-tag#32]
The documentation shows a methods object in registration, but doesn't explain it's purpose.  Any functions placed on this object belong to the xtag object in the element's instance.  I noticed in the examples that these are typically used for actions that you perform from javascript.

Another way of achieving the same things is to set a getter for a function like so:

``` javascript
getters: {
  'someFunc': function() {
    return function() {
      return "hello world";
    };
  }
}
```

What is the reason for putting a function in the methods object rather than in the getters?

**Comment by csuwildcat** [comment]
I feel this would be inappropriately hijacking what getters are intended for, plus, if you were to return a function, you would need to bind a reference to the element on that returned function, or else it is just globally scoped ;)

**Comment by matthewp** [comment]
Very good point!

My thinking is that by putting functions on the xtag object you are requiring all consumers of the widget to know about x-tags.

Also, I don't see why data and functions should be in two separate namespaces, but that is just me.  Glad to know how it's supposed to work though, thank you.
