### ISSUE TITLE
In Firefox 13.0.1 (Ubuntu Linux), "xtag.extendElement" is only called when "document.createElement" is called explicitly

### ISSUE THREAD

**Issue by Pointy** [x-tag/x-tag#38]
The x-tag examples page demonstrates that Linux Firefox does not seem to invoke the shimmed "createElement" function as HTML is parsed, either at page load time or when setting innerHTML.  Thus, the library can't do its thing. (The "register" mechanism etc. all seem fine.)

I suspect this is a platform issue.

**Comment by csuwildcat** [comment]
I'll test it, I'm betting it is an issue with CSS Animations (using that for parse detection)

**Comment by Pointy** [comment]
It's bug 765445 in the mozilla bugzilla database.

**Comment by Pointy** [comment]
If I use 0.001s instead of 0.0001s as the animation delay, things seem to work.

**Comment by csuwildcat** [comment]
I am updating the xtag.js today with the new timing value.

**Comment by csuwildcat** [comment]
@Pointy - The suggested fix - changing the animation duration to 0.001s - was pulled in a few days ago, can you double check to ensure it fixed the issue you were seeing?

**Comment by csuwildcat** [comment]
Closing this out as we no longer use this detection method
