### ISSUE TITLE
add hidden submenu flyout component

### ISSUE THREAD

**Issue by kumar303** [x-tag/x-tag#39]
Currently in HTML/CSS/JS is takes some boilerplate code to create a submenu that is hidden until you hover or click to activate. Is there a component already for this? If not, it would be a nice addition. The Action Bar looks similar but not quite the same.

Take this for example:

```
<ul>
  <li>
    <a href="#">[show menu]</a>
    <ul class="hidden submenu">
      <li>Log out</li>
      <li>Preferences</li>
      <li>Change password</li>
    </ul>
  </li>
</ul>
```

To set this up you have to do this kind of stuff:
- set up relative/absolute positioning between the menu opener and the hidden submenu
- add mouseenter/mouseout behavior to keep it open and hide it when not in use
- check to make sure the menu is not displaying off screen
- make sure it works right for mobile devices where hover doesn't apply
- maybe fiddle with z-indexing

What about this:

```
<x-submenu data-flyout-position="bottom">
  <ul>
    <li>
      <a href="#">[show menu]</a>
      <ul>
        <li>Log out</li>
        <li>Preferences</li>
        <li>Change password</li>
      </ul>
    </li>
  </ul>
</x-submenu>
```

**Comment by fwenzel** [comment]
I like the feature suggestion!

One question I have about the proposed syntax is, does it even make sense to have the outside ul/li pair? Would it perhaps make more sense to have inside tags (like `<x-submenu-trigger>` containing the thing you should click to open the submenu, and `<x-submenu-content>` holding the actual submenu content)?

**Comment by kumar303** [comment]
I defer to someone who has more experience building flyout submenus :) I think the key would be to not reinvent the wheel since ul/ol/li already provides a well supported base to work from. Maybe we can simply add data attributes or something.

**Comment by dennismartensson** [comment]
Me and @cavedweller have committed a pull request for a dropdown element, https://github.com/csuwldcat/moz-x-tags/pull/4

**Comment by pennyfx** [comment]
Closing.  This was resolved over at x-tag-elements.
