### ISSUE TITLE
flickering slide box

### ISSUE THREAD

**Issue by benbrittain** [x-tag/x-tag#44]
When you toggle the Orientation on firefox the image flickers. This only happens when you are not on the first slide. The issue does not occur in chrome. I think it might have to do with the switching of the width/height.

**Comment by csuwildcat** [comment]
Yeah, we observed that in Firefox when we created it, not sure why the width/height setting has such a visually jarring change there. Can you investigate further and develop a fix?

**Comment by benbrittain** [comment]
Do you want me to find a different way to go about sliding, or would you rather I go to the root and solve the (I assume)firefox bug? (that would be intense)

I'll see what I can do, It might be a bit beyond me though.

**Comment by csuwildcat** [comment]
I think it is a style setting oddity with Firefox, just try to tweak that section somehow and workaround it (I'd prefer not to have the code change dramatically, but go with whatever works)

**Comment by dennismartensson** [comment]
I have committed a pull request for this

 https://github.com/csuwldcat/moz-x-tags/pull/7

**Comment by pennyfx** [comment]
Closing, resolved at csuwldcat/moz-x-tags/
