### ISSUE TITLE
scrollable list view

### ISSUE THREAD

**Issue by kumar303** [x-tag/x-tag#46]
Android has a scrollable [list view](http://developer.android.com/guide/topics/ui/layout/listview.html) that lets an app screen expose a list of items. Here is an [example](http://www.mkyong.com/android/android-listview-example/). It is one of the most common views for Android apps. It would be nice to provide an xtag for this so that apps can render a list view without having to think about the styles or behaviors. To make a scrollable list view from scratch (without xtag) you have to think about these things:
- to get scrolling working right you have to fiddle with [overflow styles](http://www.domedia.org/oveklykken/css-div-scroll.php)
- you have to style the list items to look menu-like
- you have to turn anchor tags into large block click targets
- you'd want to fill the width/height of the parent (on mobile, probably the whole screen)

A list view xtag might be defined like this:

```
<x-listview>
  <ul>
    <li><a href="/item1">Item 1</a></li>
    <li><a href="/item2">Item 2</a></li>
  </ul>
</x-listview>
```

**Comment by pennyfx** [comment]
Implemented
