### ISSUE TITLE
support require.js

### ISSUE THREAD

**Issue by jlongster** [x-tag/x-tag#48]
Dan, can you work with James Burke and figure out the best way to provide x-tags as AMD modules that work with require.js?

Our app templates use require.js and we can't integrate x-tags until it works with it. I haven't talked to James yet (he's on PTO until tomorrow I think), but we need to start the conversation.

When used as a module, it seems like DOM nodes will be created before the library is fully installed (we want things async anyway), so will this still work as expected or do we need to do something to make that work?

**Comment by jrburke** [comment]
I'm happy to help. I'm on a trip at the moment, but I will be back in full work mode next week.

First thought, not sure if it makes sense: maybe allow xtags.register() to do a scan of the dom for any tags that match that tag name, if xtags already detects domcontentloaded.

But I am still very new to the x-tags code, so that may not be an appropriate path.

**Comment by jrburke** [comment]
I suppose that suggestion is only about async loaded tag implementations, there is still the matter of:
- how x-tags adapts to being loaded possibly after domcontentloaded
- if x-tags should register as an AMD module, maybe by using a pattern like [this one](https://github.com/umdjs/umd/blob/master/amdWebGlobal.js).

I can help with a pull request with some design guidance on what is wanted.

**Comment by csuwildcat** [comment]
No actually the AMD require scheme shouldn't be an issue. The tags needn't be registered according to any racy time constraint. You could have a page sitting loaded for 5 minutes and load the tags and they would parse and augment themselves instantly. All we need, is to ensure the actual 2.4k core of X-Tag is loaded before any individual tag registry occurs.

**Comment by jrburke** [comment]
OK great. So then the only thing that may be considered is if xtag would want to optionally call define() to export the xtag value. I did this pull request to show how that might be done, if that is of interest:

https://github.com/mozilla/x-tag/pull/51

I tested that in a sample AMD project and it works, the amd module that references require('x-tag') gets the local reference.

**Comment by fwenzel** [comment]
Is this issue fixed?

**Comment by pennyfx** [comment]
Yes, it was added last week if I recall correctly.
