### ISSUE TITLE
Core library not working on iPhone 4 (and perhaps other mobile devices)

### ISSUE THREAD

**Issue by karthikv** [x-tag/x-tag#54]
Receiving a "can't find variable: HTMLUnknownElement" error in the Safari debug console on iOS 5.0. I'm currently running commit https://github.com/mozilla/x-tag/commit/b1a2f6776a69f1bf6d42d0ce25912dc002601787 of x-tags. This error is still present even after the "added observe method, fixed event.target missing arg" https://github.com/mozilla/x-tag/commit/bbfce508870f19cc57fa0ad7acab856a5159ff28 commit.

**Comment by csuwildcat** [comment]
Can you do me a favor and comment out the block in x-tag.js that does the
HTMLUnknownElement method wrap and see what happens without it?

**Comment by karthikv** [comment]
It works fine when the HTMLUnknownElement method wrap is commented out. Also, when I log the result of `document.createElement('unknown-element')`, I get `[object HTMLElement]` rather than `[object HTMLUnknownElement]`.

**Comment by csuwildcat** [comment]
As I suspected, bummer. I'll need to figure out a work around for that,
until we have one you can just comment it out in your branch and continue
dev.

Important: the 'attribute' setter pseudo helper will not work with that
code commented out.

**Comment by csuwildcat** [comment]
Please update your copy of the base js and test this, I believe it is fixed.

**Comment by karthikv** [comment]
Yep, it's working for me! Closing the issue.
