### ISSUE TITLE
Double onInsert triggers

### ISSUE THREAD

**Issue by geddski** [x-tag/x-tag#55]
`onInsert` is triggering twice for each element. See example: http://jsbin.com/ezivuw/31/edit
Tested in both Firefox and Chrome.

**Comment by csuwildcat** [comment]
I'll take a look at this tomorrow to verify/debug, thank you for the report.

**Comment by fwenzel** [comment]
Tests! &lt;/captainobvious&gt;

**Comment by geddski** [comment]
@fwenzel didn't write a test, just the example. I'll write a test later if I get time.

**Comment by fwenzel** [comment]
@geddesign no sweat, my short comment was directed at @csuwldcat, gently nudging to ensure we have tests for the correct behavior of the x-tags core (and probably even the individual tags).

**Comment by csuwildcat** [comment]
This should now be fixed with this commit: https://github.com/mozilla/x-tag/commit/a73804fc79bea713102eb168f0f1140342fdf850

@geddesign if you can test the new version of x-tag.js and confirm, I'd be much obliged ;)

**Comment by geddski** [comment]
fixed! Nicely done. 

http://jsbin.com/ezivuw/46/edit
