### ISSUE TITLE
elements submodule reference is broken

### ISSUE THREAD

**Issue by jlongster** [x-tag/x-tag#61]
The "elements" repo reference is broken. If you try to clone recursively or do any submodule operations, you get:

No submodule mapping found in .gitmodules for path 'elements'

**Comment by jlongster** [comment]
Seems like .gitmodules needs to be committed.

**Comment by zalun** [comment]
Is there a different way to install x-tags locally?

**Comment by csuwildcat** [comment]
We're about to remove the "elements" submodule from x-tag main repo,
perhaps download this: https://github.com/mozilla/xtag-elements ?

**Comment by pennyfx** [comment]
Elements reference has been removed.  See mozilla/x-tag-elements
