### ISSUE TITLE
Create comprehensive test suite

### ISSUE THREAD

**Issue by daviddahl** [x-tag/x-tag#62]
I was just looking through the code and do not see a test suite. All Mozilla code needs to have a test suite, especially if this code is being used in production. Also, multiple reviewers should go over this code, but perhaps not until there is a test suite.

**Comment by fwenzel** [comment]
Do we know what Gaia uses to test their components? I am open to many options, but perhaps not deviating from their test suite would be beneficial.

**Comment by fwenzel** [comment]
@autonome can you advise?

**Comment by fwenzel** [comment]
(I realize x-tags[the library] is different from the UI components, but they could still be tested with the same test runner).

**Comment by autonome** [comment]
@lightsofapollo yo, can you link the Gaia test frameworks here?

**Comment by lightsofapollo** [comment]
We use a combination of https://github.com/visionmedia/mocha + http://chaijs.com/

Full details here: https://developer.mozilla.org/en-US/docs/Mozilla/Boot_to_Gecko/Gaia_Unit_Tests

We have some special extensions for running tests across multiple domains with extra niceties like reporting browser tests results to a console, auto-running tests, and more through https://github.com/lightsofapollo/js-test-agent (which is more or less a more sophisticated runner test runner for mocha)

**Comment by pennyfx** [comment]
We chose to use jasmine for the time being.  Mocha looks cool and has a similar test interface, so we may move to that if we need more functionality in the future.
