### ISSUE TITLE
Twitter button spies on users

### ISSUE THREAD

**Issue by seanmonstar** [x-tag/x-tag#63]
It's possible to allow a tweet button that forwards to Twitter, without pulling in the Twitter javascript from `platform.twitter.com`. Twitter knowingly tracks users with their widgets. Boo.

**Comment by csuwildcat** [comment]
You're in luck, just the other day we decided to accept pull requests!
Tw(f)ix that shizzle!

**Comment by fwenzel** [comment]
Where's the code for x-tags.org?

**Comment by fwenzel** [comment]
Moved to xtags-org issue 1: https://github.com/mozilla/xtags-org/issues/1
