### ISSUE TITLE
README.md file has a pasto in git clone

### ISSUE THREAD

**Issue by kaladron** [x-tag/x-tag#64]
If you're interested in exploring the tags we've already created, check out our x-tag-elements repository.

```
git clone --recursive https://github.com/mozilla/x-tag
```

should read "x-tag-elements" at the end of the git clone line.

**Comment by fwenzel** [comment]
@pennyfx you fixed this, right? Will you close this Issue if that's true?

**Comment by pennyfx** [comment]
Fixed
