### ISSUE TITLE
Setter causes recursion error

### ISSUE THREAD

**Issue by jlubean** [x-tag/x-tag#65]
The following code causes a "too much recursion" error in Firefox and a "RangeError: Maximum call stack size exceeded" error in Chrome:

``` javascript
xtag.register('mytag', {
  setters: {
    myValue: function(value) {
      this.myValue = value;
    }
  }
});

var e = document.createElement("mytag");
e.myValue = "A value";
```

**Comment by pennyfx** [comment]
Yes, it is because you're calling your setter inside of the setter.     If you are trying to save the passed value then you need to explicitly save it somewhere.  For example, use a data attribute `this.dataset.myValue = value`.

**Comment by jlubean** [comment]
On x-tag.org, the setters example will cause a recursion error.  I added issue 66.
