### ISSUE TITLE
Different from Spec

### ISSUE THREAD

**Issue by bhazzard** [x-tag/x-tag#81]
Functionality-wise, this is really cool. But, it seems significantly different from the Web Components custom element spec defined at https://dvcs.w3.org/hg/webcomponents/raw-file/tip/explainer/index.html.

Am I misunderstanding something?

**Comment by csuwildcat** [comment]
This is X-Tag, the higher-level lib that sits on top of the
document.register, the polyfill for the spec'd document.register interface
is at github.com/mozilla/web-components - X-Tag relies upon it.
- Daniel

**Comment by csuwildcat** [comment]
This is also old code for X-Tag, it is now located at github.com/x-tag the lib is under the 'core' repo.
