### ISSUE TITLE
Support for Decorators?

### ISSUE THREAD

**Issue by bhazzard** [x-tag/x-tag#82]
As I understand it, this is intended to implement just custom elements. But, it seems like decorators are actually the more powerful feature of the Web Components spec. I say this because they allow for Plain-Old-Semantic-HTML (POSH), but also rich user interfaces. It's like best of both worlds.

Any plans to implement decorators?

**Comment by csuwildcat** [comment]
It may be possible, and we would certainly accept pull requests ;)
