### ISSUE TITLE
Each component needs its own DOMComponentLoaded event

### ISSUE THREAD

**Issue by smcmurray** [x-tag/x-tag#83]
From within my DOMComponentsLoaded event handler, the methods of my component are still undefined.

**Comment by csuwildcat** [comment]
Can you post a simplified test case?

**Comment by smcmurray** [comment]
As explained by @csuwldcat, the DOMComponentsLoaded event fires once per scope. It will only be fired for things that are in the document as loaded. Adding X-tag to the document after load (through an AMD loader, for instance) will mean that would-be web components that rely on X-tag for their registration will be registered too late for the DOMComponentsLoaded event.

That leaves them caught out. They are too late for DOMComponentsLoaded, but may still not be intialized before the AMD loaded script is ready to interact with them.

It might be helpful for each component to get a DOMComponentLoaded event.
