### ISSUE TITLE
Broken link to brick project

### ISSUE THREAD

**Issue by kaleb** [x-tag/x-tag#86]
This is actually a bug for the x-tags website, but i was unsure where to file it.

On the x-tags.org there is a link called Brick with the href of http://mozilla.github.io/brick/ which is broken. This website returns a 404 and the corresponding github repo is non-existent.

**Comment by tofumatt** [comment]
I opened a pull request; the x-tags site is in https://github.com/x-tag/x-tags-org/. Sorry for the confusion. Thanks for catching this!
